bdBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: bdBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomusr:
            type: string
            length: '15'
            nullable: true
            unique: true
        pass:
            type: string
            length: '20'
            nullable: true
        nomcom:
            type: string
            length: '100'
            nullable: true
        numafil:
            type: string
            length: '10'
            unique: true
        curp:
            type: string
            length: '18'
            nullable: true
            unique: true
        numtra:
            type: string
            length: '10'
            unique: true
        telefono:
            type: string
            length: '10'
        email:
            type: string
            length: '100'
        idtipo:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
