bdBundle\Entity\Usuarios:
    type: entity
    table: null
    repositoryClass: bdBundle\Repository\UsuariosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        email:
            type: string
            length: '100'
        pass:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
