<?php

namespace bdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipousuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipousuRepository extends EntityRepository
{
}
